- name: Install Web Server 
  package:
    name: httpd
    state: present

- name: Copy studentapp condifuration
  copy:
    src: studentapp.conf
    dest: /etc/httpd/conf.d/studentapp.conf

- name: Download default index file 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html/index.html
    