- name: Become a root user
  hosts: all
  tasks: 
    - name:  id command 
      shell: id
      register: out1

    - debug:
        msg: "{{out1}}"

    - name: id command as root user
      shell: id
      register: out2

    - debug:
        msg: "{{out2}}"
        