- name: Demo on when conditions 
  hosts: all 
  become: yes
  tasks:
    - name: Install web server on ubuntu
      package:
        name: apache2
        state: present

    - name: Install web server on centos
      package:
        name: httpd
        state: present