- name: demo on loops
  hosts: centos
  become: yes
  tasks:
    - name: Installing Packages
      package:
        name: "{{item}}"
        state: present
      loop: ## Loop with list of values
        - httpd
        - vim 
        - unzip